name: Publish PDF to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Typst
        uses: typst-community/setup-typst@v4

      - name: Build PDF
        run: |
          mkdir output
          typst compile main.typ output/polimi_thesis.pdf

      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
